export const CHANGEMASK = 'character/CHANGEMASK'
export const TOGGLEMASKFILTER = 'character/TOGGLEMASKFILTER'
export const CHANGECHARACTER = 'character/CHANGECHARACTER'
export const CHANGEARMOUR = 'character/CHANGEARMOUR'
export const CHANGEEQUIPMENT = 'character/CHANGEEQUIPMENT'